version: '3.7'
services:
  frontend:
    container_name: acs-beauty-front
    build: .
    restart: always
    volumes:
      - '.:/app'
    ports:
      - 80:80
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true