import { FC } from "react";
import Head from "next/head";

import Navigation from "../Navigation";
import DeliveryBanner from "../DeliveryBanner";
import Header from "../../UI/Header";
import Footer from "../../UI/Footer";
import { UserLayoutPropsType } from "@/types/components";

const UserLayout: FC<UserLayoutPropsType> = ({
  title,
  children,
  categories,
}) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DeliveryBanner />
      <Header />
      <Navigation categories={categories} />
      <main>{children}</main>
      <Footer />
    </>
  );
};

export default UserLayout;
